# Generated by Django 6.0.6 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('yosh', models.CharField(blank=True, max_length=50, null=True)),
                ('shahar', models.CharField(blank=True, max_length=100, null=True)),
                ('yozilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('haqida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquvchi_ismi', models.CharField(max_length=100)),
                ('fikri', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='natijalar/')),
            ],
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('savol_matni', models.TextField()),
                ('yozilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavolJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=255)),
                ('javob', models.TextField()),
            ],
        ),
    ]
